### ISSUE TITLE
Getting compilation error as Input length = 1

### ISSUE THREAD

**Issue by shaziyasyd** [sangria-graphql/sangria-playground#19]
Hi I was using Sangria with Scala & Play framework.

I am getting this error on compilation.
`[info] Compiling 1 Scala source to /Users/shaziyasyeda/Projects/bcg/scala-graphql-demo/target/scala-2.12/classes ...
[error] Input length = 1
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 4 s, completed 3 May, 2019 7:44:04 PM

Here's the code that's causing this error.
`Executor.execute(BooksSchema.schema, queryAst, new BooksServiceImpl,
          variables = variables getOrElse Json.obj(),
          deferredResolver = DeferredResolver.fetchers(BooksSchema.books),
          exceptionHandler = exceptionHandler,
          queryReducers = List()
        ).map(Ok(_))`

When I comment this out, it compiles successfully.

Any help would be appreciated.
`

**Comment by nickhudkins** [comment]
Hi @shaziyasyd as this issue does not strictly pertain to this project, I am going to go ahead and close this issue. Let me know if you're having trouble running this project in its latest state and I am happy to help.
