### ISSUE TITLE
try.sangria-graphql.org returns 404

### ISSUE THREAD

**Issue by levinotik** [sangria-graphql/sangria-playground#21]
Not sure that opening an issue is the right way to report this, but the Try website doesn't seem to be reachable. 

![image](https://user-images.githubusercontent.com/514174/67622661-557a5800-f7ea-11e9-8760-bc5f715beda2.png)

**Comment by muety** [comment]
Happening again, now. I'd appreciate it if the playground could be brought up again! 🙂

**Comment by yanns** [comment]
https://github.com/sangria-graphql/sangria/issues/446#issuecomment-623075358

**Comment by nickhudkins** [comment]
Removed for now as we don't own the domain, but you can try out Sangria (specifically build with akka-http here: https://sangria-example.herokuapp.com/graphql)
