### ISSUE TITLE
Where's the code for mutations?

### ISSUE THREAD

**Issue by AlexGilleran** [sangria-graphql/sangria-playground#9]
Sorry if I'm missing something major here. The actual live site has an "introduceShip" mutation, but I can't find it in the code anywhere. Is this up to date with what's on http://try-relay.sangria-graphql.org/ ?

**Comment by AlexGilleran** [comment]
Ok so I think I'm looking for https://github.com/sangria-graphql/sangria-relay-playground/blob/master/app/models/SchemaDefinition.scala, but got led here by the link in http://try-relay.sangria-graphql.org/ - maybe that should be updated? Bit confused about which one is supposed to do what. Closing.

**Comment by OlegIlyenko** [comment]
Thanks for reporting this! I fixed the link: https://github.com/sangria-graphql/sangria-relay-playground/commit/3949b9423a4256ca6aace241444f3ee42ee678bc

**Comment by AlexGilleran** [comment]
Great, thanks Oleg :)
